FILES = ProducerConsumer.java Producer.java Consumer.java Buffer.java
all: 
	javac -g $(FILES)
run: 
	java ProducerConsumer
clean: 
	rm *.class
package:
	zip -r Sky-Vercauteren-HW4.zip ProducerConsumer.java Producer.java Consumer.java Buffer.java Makefile README.txt